### hello
GET http://localhost:8080/hello

### Gateway
GET http://localhost:8080/gw

### POST user
POST http://localhost:8080/gw/com.cola.kfcrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.cola.kfcrpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [21,"cola"]
}